spring:
  application:
    name: event-processor

  main:
    web-application-type: none

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: pulseops-event-processor
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

      acks: all

      properties:
        enable.idempotence: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

pulseops:
  ai:
    base-url: ${PULSEOPS_AI_BASE_URL:http://localhost:8000}

  prometheus:
    base-url: ${PULSEOPS_PROMETHEUS_BASE_URL:http://localhost:9090}

  tempo:
    base-url: ${PULSEOPS_TEMPO_BASE_URL:http://localhost:3200}

management:
  endpoints:
    web:
      exposure:
        include: health,info