package com.pulseops.api.incident.service;

import java.util.UUID;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.pulseops.api.incident.dto.CreateIncidentRequest;
import com.pulseops.api.incident.dto.IncidentResponse;
import com.pulseops.api.incident.entity.Incident;
import com.pulseops.api.incident.entity.IncidentStatus;
import com.pulseops.api.incident.repository.IncidentRepository;
import com.pulseops.api.outbox.service.OutboxService;
import com.pulseops.common.events.IncidentDetectedEvent;

@Service
public class IncidentService {

    private final IncidentRepository incidentRepository;
    private final OutboxService outboxService;

    public IncidentService(
            IncidentRepository incidentRepository,
            OutboxService outboxService) {

        this.incidentRepository = incidentRepository;
        this.outboxService = outboxService;
    }

    @Transactional
    public IncidentResponse createIncident(
            CreateIncidentRequest request) {

        Incident incident = new Incident();

        incident.setIncidentKey(
                generateIncidentKey()
        );

        incident.setTitle(request.title());
        incident.setDescription(request.description());
        incident.setSeverity(request.severity());
        incident.setStatus(IncidentStatus.OPEN);
        incident.setServiceName(request.serviceName());

        Incident savedIncident =
                incidentRepository.save(incident);

        outboxService.createIncidentCreatedEvent(
                savedIncident
        );

        return IncidentResponse.from(
                savedIncident
        );
    }

    @Transactional
    public void createIncidentFromDetection(
            IncidentDetectedEvent event) {

        /*
         * Detection events already contain the incident identity
         * generated by the correlation engine, so we preserve it
         * instead of creating a second identifier.
         */
        Incident incident = new Incident();

        incident.setIncidentKey(
                event.incidentKey()
        );

        incident.setTitle(
                event.title()
        );

        incident.setDescription(
                event.description()
        );

        incident.setSeverity(
                com.pulseops.api.incident.entity.IncidentSeverity
                        .valueOf(event.severity())
        );

        incident.setStatus(
                IncidentStatus.OPEN
        );

        incident.setServiceName(
                event.serviceName()
        );

        Incident savedIncident =
                incidentRepository.save(incident);

        outboxService.createIncidentCreatedEvent(
                savedIncident
        );
    }

    private String generateIncidentKey() {

        return "INC-"
                + UUID.randomUUID()
                        .toString()
                        .substring(0, 8)
                        .toUpperCase();
    }
}